### ISSUE TITLE
Deploying new instances seems to be broken?

### ISSUE THREAD

**Issue by brianjking** [ALinuxNinja/openshift-cachet#1]
I was trying to deploy a new instance today and it would show as "deploying..." and then would disappear. Any idea if something is broken or is it just my account? @ALinuxNinja 

Thanks!

**Comment by eveandcats** [comment]
Script does deploy, but after starting, it dies.

From what I can see, it's because the script is attempting to pull Cachet v2-beta2, which doesn't seem to work with this version of openshift-cachet.

I'll push a quick fix in a while to avoid downloading v2 until I can get it working.

**Comment by eveandcats** [comment]
Fixed the deployment script, and testing it seems to work.

Let me know if there are any other issues :)

**Comment by brianjking** [comment]
@ALinuxNinja Thanks, I was able to deploy the instance. Can't wait to see a fix for Version 2.

Thanks for all that you do!
