### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by Neruell** [ALinuxNinja/openshift-cachet#3]
This is not really an issue with this code or repo. Deploying and running works totally fine on openshift, though I would like to add a plugin to cachet the cachet-monitor. 

(https://github.com/CastawayLabs/cachet-monitor)

Although I am not sure how to do it on openshift since the plugin seems to rely on golang but it is impossible to add golang to the application created with this repo because of multiple web cartridges. So I am not sure, is there any other way to add the plugin to cachet on openshift?

**Comment by eveandcats** [comment]
Should work fine if you download go into the data directory and run from there.

Just tried this:

```
cd ~/app-root/data
wget https://storage.googleapis.com/golang/go1.5.2.linux-amd64.tar.gz
tar xvf go1.5.2.linux-amd64.tar.gz
rm go1.5.2.linux-amd64.tar.gz
mkdir goapp
cd go/bin
GOPATH=~/app-root/data/goapp GOROOT=~/app-root/data/go ./go get github.com/castawaylabs/cachet-monitor
GOPATH=~/app-root/data/goapp GOROOT=~/app-root/data/go ./go install github.com/castawaylabs/cachet-monitor
```

You can now find cachet-monitor in ~/app-root/data/goapp/bin/cachet-monitor. It's not in the PATH, so you will have to run it with ./cachet-monitor

You may want to fork the repo and make your own modifications for more convenience if you want it to be automated.

**Comment by Neruell** [comment]
Thanks a lot. Really helped me :)

**Comment by hmnd** [comment]
@ALinuxNinja I followed your instructions, however, there doesn't seem to be any directory called cachet-monitor in the ~/app-root/data/goapp/bin/ directory...

**Comment by eveandcats** [comment]
This step has not been required for a while, simply because you can download builds directly at https://github.com/CastawayLabs/cachet-monitor/releases

cachet-monitor_linux_amd64 seems to work fine if you chmod it 755
