### ISSUE TITLE
Location of env file once deployed to Openshift

### ISSUE THREAD

**Issue by brianjking** [ALinuxNinja/openshift-cachet#4]
Hi,

I wanted to enable the emoji option in Cachet as per https://docs.cachethq.io/docs/github-oauth-token. However, I am stuck on locating the `env` file once I have deployed Cachet to Openshift?

Thanks!

**Comment by eveandcats** [comment]
It should be in `$OPENSHIFT_REPO_DIR/Cachet/.env`

**Comment by brianjking** [comment]
@ALinuxNinja Thanks, I got it working.

Will this be overwritten everytime I use your update script or will it remain functional between versions?

Thanks!

**Comment by eveandcats** [comment]
The update script copies the old .env back to `$OPENSHIFT_REPO_DIR/env` before upgrading, and puts it back afterwards, so it should keep the edits that you made

**Comment by brianjking** [comment]
@ALinuxNinja Thanks
