### ISSUE TITLE
Using Cachet Email Subscribe 

### ISSUE THREAD

**Issue by brianjking** [ALinuxNinja/openshift-cachet#5]
@ALinuxNinja Any idea why the Configuring Email subscribe doesn't seem to work with Mailgun as per the Cachet docs? Have you been able to do this via your Openshift deployment?
- https://cachet.readme.io/docs/configuring-mail
- https://cachet.readme.io/docs/setup-subscribers

Thanks!

**Comment by eveandcats** [comment]
I haven't ever tested that, am working on seeing what the issue is at the moment. Mailgun seems to be having a few issues validating my domain so I am waiting on them to complete that.

**Comment by brianjking** [comment]
Thanks @ALinuxNinja.

I was wondering about the following:

```
APP_ENV=local
APP_DEBUG=true
APP_URL=http://primrose.com
```
- Why is `APP_ENV` set to local and not production?
- What is primrose.com?

Thanks!

**Comment by eveandcats** [comment]
APP_ENV should be set to production, I have corrected the mistake.

APP_URL is a placeholder, you can change it to anything you want. I've considered changing it to the openshift application URL, I will add that to the list of things I should update.

**Comment by eveandcats** [comment]
All fixed on new deployments.

Cachet uses a cron job to send mail out periodically, which I was not aware of. A cron job has been added now and tested to send SMTP mail (mailgun still verifying my domain)

**Comment by brianjking** [comment]
Yeah, you can also set Cachet to use the sync method without the cronjob which was what I was trying to do. 

Is there a way to add the cronjob to an existing deployment?

**Comment by eveandcats** [comment]
Add https://github.com/ALinuxNinja/openshift-cachet/blob/master/.openshift/cron/minutely/db_queue in $OPENSHIFT_REPO_DIR/.openshift/cron/minutely/db_queue and make it executable.

Then, you should be able to add the cron cartridge via https://blog.openshift.com/getting-started-with-cron-jobs-on-openshift/

**Comment by brianjking** [comment]
@ALinuxNinja I added the cron cartridge as well as that file and cleared the cache and still the subscribe button didn't appear.

I tried to launch a new instance as well and configured mailgun and still didn't show. Did your instance show the subscribe option once enabling it in the dashboard admin area?

Thanks!

**Comment by eveandcats** [comment]
No, I saw your issue about that earlier in the Cachet repo. The cron does not have anything to do with the subscribe button, only sending mail. The subscribe button does not show up on mine either, so I will do some testing to see what is going on.

Update #1:

I tested Cachet using their official docker application at https://github.com/CachetHQ/Docker. Upon deploying and allowing users to subscribe, there is no subscribe button after logging out.

**Comment by brianjking** [comment]
@ALinuxNinja Please check out https://github.com/CachetHQ/Cachet/issues/1686#issuecomment-206474040

**Comment by eveandcats** [comment]
Fixed, had some old code installing composer libraries from source instead of dist

**Comment by brianjking** [comment]
@ALinuxNinja So it's working now? What can I do to get it working on an existing install? Thanks!

**Comment by eveandcats** [comment]
Give the following a try:

```
cd $OPENSHIFT_REPO_DIR/Cachet/
mv vendor vendor-old
$OPENSHIFT_PHP_VERSION_DIR/bin/php $OPENSHIFT_DATA_DIR/bin/composer.phar install --prefer-dist --no-interaction
```

Any non-null mail settings + enabling subscribing will make the subscribe button show up.

**Comment by brianjking** [comment]
@ALinuxNinja I actually didn't have to run this command, not sure why. However, I have one site now working with the `sync` method and one with the `database` method as described at https://cachet.readme.io/docs/setup-subscribers.

Thanks so much!

**Comment by Si-Richards** [comment]
I'm getting the same issue. I followed these instructions.... 
tweaked for the latest branch and no subscription button. It's enabled in the backend....
